/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.gdcr.technowise

class Calculator {
    fun add(firstInt: Int, secondInt: Int) = firstInt + secondInt
}

fun main(args: Array<String>) {
    val firstInt = 4
    val secondInt = 2
    val calculator = Calculator()
    println("Sum of $firstInt and $secondInt = ${calculator.add(firstInt, secondInt)}")
}
